require("CVarManager.lua")
require("CCommandManager.lua")

StringToKeyMap =
{
	["a"] = jar.Key.A,
	["b"] = jar.Key.B,
	["c"] = jar.Key.C,
	["d"] = jar.Key.D,
	["e"] = jar.Key.E,
	["f"] = jar.Key.F,
	["g"] = jar.Key.G,
	["h"] = jar.Key.H,
	["i"] = jar.Key.I,
	["j"] = jar.Key.J,
	["k"] = jar.Key.K,
	["l"] = jar.Key.L,
	["m"] = jar.Key.M,
	["n"] = jar.Key.N,
	["o"] = jar.Key.O,
	["p"] = jar.Key.P,
	["q"] = jar.Key.Q,
	["r"] = jar.Key.R,
	["s"] = jar.Key.S,
	["t"] = jar.Key.T,
	["u"] = jar.Key.U,
	["v"] = jar.Key.V,
	["w"] = jar.Key.W,
	["x"] = jar.Key.X,
	["y"] = jar.Key.Y,
	["z"] = jar.Key.Z,
	["0"] = jar.Key.Num0,
	["1"] = jar.Key.Num1,
	["2"] = jar.Key.Num2,
	["3"] = jar.Key.Num3,
	["4"] = jar.Key.Num4,
	["5"] = jar.Key.Num5,
	["6"] = jar.Key.Num6,
	["7"] = jar.Key.Num7,
	["8"] = jar.Key.Num8,
	["9"] = jar.Key.Num9,
	["escape"] = jar.Key.Escape,
	["lcontrol"] = jar.Key.LControl,
	["lshift"] = jar.Key.LShift,
	["lalt"] = jar.Key.LAlt,
	["lsystem"] = jar.Key.LSystem,
	["rcontrol"] = jar.Key.RControl,
	["rshift"] = jar.Key.RShift,
	["ralt"] = jar.Key.RAlt,
	["rsystem"] = jar.Key.RSystem,
	["menu"] = jar.Key.Menu,
	["lbracket"] = jar.Key.LBracket,
	["rbracket"] = jar.Key.RBracket,
	["semicolon"] = jar.Key.SemiColon,
	["comma"] = jar.Key.Comma,
	["period"] = jar.Key.Period,
	["quote"] = jar.Key.Quote,
	["slash"] = jar.Key.Slash,
	["backslash"] = jar.Key.BackSlash,
	["tilde"] = jar.Key.Tilde,
	["equal"] = jar.Key.Equal,
	["dash"] = jar.Key.Dash,
	["space"] = jar.Key.Space,
	["return"] = jar.Key.Return,
	["backspace"] = jar.Key.BackSpace,
	["tab"] = jar.Key.Tab,
	["pageup"] = jar.Key.PageUp,
	["pagedown"] = jar.Key.PageDown,
	["end"] = jar.Key.End,
	["home"] = jar.Key.Home,
	["insert"] = jar.Key.Insert,
	["delete"] = jar.Key.Delete,
	["add"] = jar.Key.Add,
	["subtract"] = jar.Key.Subtract,
	["multiply"] = jar.Key.Multiply,
	["divide"] = jar.Key.Divide,
	["left"] = jar.Key.Left,
	["right"] = jar.Key.Right,
	["up"] = jar.Key.Up,
	["down"] = jar.Key.Down,
	["numpad0"] = jar.Key.Numpad0,
	["numpad1"] = jar.Key.Numpad1,
	["numpad2"] = jar.Key.Numpad2,
	["numpad3"] = jar.Key.Numpad3,
	["numpad4"] = jar.Key.Numpad4,
	["numpad5"] = jar.Key.Numpad5,
	["numpad6"] = jar.Key.Numpad6,
	["numpad7"] = jar.Key.Numpad7,
	["numpad8"] = jar.Key.Numpad8,
	["numpad9"] = jar.Key.Numpad9,
	["f1"] = jar.Key.F1,
	["f2"] = jar.Key.F2,
	["f3"] = jar.Key.F3,
	["f4"] = jar.Key.F4,
	["f5"] = jar.Key.F5,
	["f6"] = jar.Key.F6,
	["f7"] = jar.Key.F7,
	["f8"] = jar.Key.F8,
	["f9"] = jar.Key.F9,
	["f10"] = jar.Key.F10,
	["f11"] = jar.Key.F11,
	["f12"] = jar.Key.F12,
	["f13"] = jar.Key.F13,
	["f14"] = jar.Key.F14,
	["f15"] = jar.Key.F15,
	["pause"] = jar.Key.Pause,
}

-- Shoot Em Up specific: key_*** (e.g. key_up) contains the name of the key for some action.
-- For renaissance, I should not do this.
function GetKey(name)
	return StringToKeyMap[g_CVarManager:GetCVarValue("key_"..name)]
end